
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// // Create storage bucket for questions if it doesn't exist
// const createQuestionsBucket = async () => {
//   try {
//     const { data: buckets } = await supabase.storage.listBuckets();
//     const questionsBucketExists = buckets?.some(bucket => bucket.name === 'questions');
    
//     if (!questionsBucketExists) {
//       // console.log("Creating questions bucket for image storage");
//       await supabase.storage.createBucket('questions', {
//         public: true, // Make it public so images can be accessed without auth
//         fileSizeLimit: 5242880, // 5MB
//       });
//     }
//   } catch (error) {
//     // console.error("Error checking/creating questions bucket:", error);
//   }
// };

// createQuestionsBucket();

// console.log("Supabase client initialized");

export default supabase;
