
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifixeorfrxithupdmasg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmaXhlb3JmcnhpdGh1cGRtYXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDM5MzMsImV4cCI6MjA2MDI3OTkzM30.QQgdq5oE1nvEqa-tu8_Y7UHX6vBD81Aep_NkmDHW3GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Create storage bucket for questions if it doesn't exist
const createQuestionsBucket = async () => {
  try {
    const { data: buckets } = await supabase.storage.listBuckets();
    const questionsBucketExists = buckets?.some(bucket => bucket.name === 'questions');
    
    if (!questionsBucketExists) {
      // console.log("Creating questions bucket for image storage");
      await supabase.storage.createBucket('questions', {
        public: true, // Make it public so images can be accessed without auth
        fileSizeLimit: 5242880, // 5MB
      });
    }
  } catch (error) {
    // console.error("Error checking/creating questions bucket:", error);
  }
};

// createQuestionsBucket();

// console.log("Supabase client initialized");

export default supabase;
